import type { TutorialGuide } from "./types";

/**
 * A deliberately short first-run guide. It teaches the core loop with real
 * controls inside the disposable tutorial state; the full guide and focused
 * modules remain available for feature depth.
 */
export const BASIC_TUTORIAL_GUIDE: TutorialGuide = {
  id: "essential",
  version: 6,
  title: "HabHub basics",
  detail: "A two-minute tour of Today, tracker history, and the controls that personalize HabHub",
  icon: "compass-outline",
  path: "/",
  sections: [
    { id: "today", title: "Today", detail: "Daily goals, to-dos and edit mode" },
    { id: "metric-detail", title: "Tracker detail", detail: "History, charts and records" },
    { id: "menu", title: "Menu", detail: "Profile and feature navigation" },
    { id: "display", title: "Display", detail: "Theme, pages, order and widget guidance" },
  ],
  steps: [
    {
      id: "essential.navigation",
      sectionId: "today",
      target: "tab-bar",
      path: "/",
      title: "Start with the navigation bar",
      copy: "The bottom bar opens HabHub's main pages. Today is your daily home; hidden optional pages can be enabled later from Display settings.",
      primaryLabel: "Show Today",
      anchor: { required: false, waitMs: 1800, padding: 0, radius: 0 },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.today.hero",
      sectionId: "today",
      target: "today-hero",
      path: "/",
      title: "Start with the daily summary",
      copy: "The featured card combines only goals you flagged as tracked. Its bars show tracked-goal completion and to-do completion, and tapping it opens Status.",
      primaryLabel: "Next",
      anchor: { required: true, waitMs: 1800, padding: 7, radius: 18 },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.today.tracked-versus-general",
      sectionId: "today",
      target: "today-tracker-list",
      path: "/",
      title: "Tracked goals and general trackers",
      copy: "A tracked goal counts toward the daily completion result. A general tracker can stay visible for logging and history without affecting that result.",
      primaryLabel: "Next",
      anchor: { required: false, waitMs: 1800 },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "essential.today.open-tracker",
      sectionId: "today",
      target: "today-steps-tracker",
      path: "/",
      title: "Open a tracker yourself",
      copy: "Every tracker tile opens its dedicated page with today's result, goals, history, records, notes, and shortcuts.",
      primaryLabel: "Tap Steps",
      anchor: { required: true, waitMs: 1800, padding: 5, radius: 16 },
      interaction: {
        mode: "practice",
        actionId: "tutorial.today.open-tracker",
        instruction: "Tap the Steps tracker to open its dedicated page.",
        completion: "observed-action",
        autoAdvance: true,
      },
    },
    {
      id: "full.metric-detail.summary",
      sectionId: "metric-detail",
      path: "/metric-detail",
      target: "metric-detail-summary",
      title: "Read one tracker's story",
      copy: "A tracker page combines the chosen day or range, current result, goal state, history visualization, records, notes, related to-dos and shortcuts to log, edit or schedule it.",
      primaryLabel: "Next",
      anchor: { required: true, waitMs: 1800, padding: 7, radius: 16 },
      navigation: { before: "/metric-detail?metric=steps" },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "essential.metric-detail.week",
      sectionId: "metric-detail",
      path: "/metric-detail",
      target: "metric-detail-week",
      title: "Switch from today to a weekly history",
      copy: "Tracker pages can show today, yesterday, week, month, year, or all history without losing the selected tracker.",
      primaryLabel: "Tap Week",
      anchor: { required: true, waitMs: 1800, padding: 5, radius: 12 },
      navigation: { before: "/metric-detail?metric=steps" },
      interaction: {
        mode: "practice",
        actionId: "tutorial.metric-detail.open-week",
        instruction: "Tap Week to load the tracker's recent history.",
        completion: "observed-action",
        autoAdvance: true,
      },
    },
    {
      id: "full.metric-detail.visuals",
      sectionId: "metric-detail",
      path: "/metric-detail",
      target: "metric-detail-chart",
      title: "Visuals follow tracker settings",
      copy: "Selected-day, range, Progress overview and grid-map visuals can use progress, completion, bars, lines, both, intensity or completion according to compatible settings.",
      primaryLabel: "Next",
      anchor: { required: true, waitMs: 1800, padding: 7, radius: 16 },
      navigation: { before: "/metric-detail?metric=steps&period=week" },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "essential.today.open-menu",
      sectionId: "menu",
      target: "menu-button",
      path: "/",
      title: "Open the menu yourself",
      copy: "The profile avatar opens HabHub's menu. Use it whenever you want tracker customization, settings, groups, notifications or guide replay.",
      primaryLabel: "Tap the profile avatar",
      anchor: { required: true, waitMs: 1800, padding: 5, radius: 18 },
      navigation: { before: "/" },
      interaction: {
        mode: "practice",
        actionId: "tutorial.navigation.open-menu",
        instruction: "Tap your profile avatar to open the menu.",
        completion: "observed-action",
        autoAdvance: true,
      },
    },
    {
      id: "essential.menu.open-display",
      sectionId: "display",
      target: "menu-display",
      path: "/menu",
      title: "Open Display settings",
      copy: "Display controls theme, text size, visible pages, tab order, landing page and the layouts used by Today and Progress.",
      primaryLabel: "Tap Display",
      anchor: { required: true, waitMs: 1800, padding: 5, radius: 14 },
      navigation: { before: "/menu" },
      interaction: {
        mode: "practice",
        actionId: "tutorial.navigation.open-display",
        instruction: "Tap Display to open the app layout controls.",
        completion: "observed-action",
        autoAdvance: true,
      },
    },
    {
      id: "essential.display.layout",
      sectionId: "display",
      target: "display-layout",
      path: "/display-settings",
      title: "Keep only what you use",
      copy: "Show, hide, or reorder optional pages here. You can replay this guide from the menu at any time.",
      primaryLabel: "Finish",
      anchor: { required: true, waitMs: 1800 },
      interaction: { mode: "observe", completion: "manual" },
    },
  ],
};

export const DEFAULT_TUTORIAL_GUIDES: readonly TutorialGuide[] = [
  BASIC_TUTORIAL_GUIDE,
];

/** Backward-compatible alias used by onboarding and guide replay. */
export const BASIC_TUTORIAL_GUIDES = DEFAULT_TUTORIAL_GUIDES;
