import type { TutorialGuide } from "./types";

/**
 * The post-onboarding guide is intentionally broad but shallow. It introduces
 * the real navigation and vocabulary first; the full guide and focused modules
 * remain available for hands-on feature depth.
 */
export const BASIC_TUTORIAL_GUIDE: TutorialGuide = {
  id: "essential",
  version: 5,
  title: "HabHub basics",
  detail: "A guided introduction to trackers, every main page, and the controls that personalize HabHub",
  icon: "compass-outline",
  path: "/",
  sections: [
    { id: "today", title: "Today", detail: "Daily goals, to-dos and edit mode" },
    { id: "menu", title: "Menu", detail: "Profile and feature navigation" },
    { id: "custom-metric", title: "Custom trackers", detail: "Creation, formulas and advanced visuals" },
    { id: "status", title: "Status", detail: "Avatar, body facts and tracked goals" },
    { id: "log", title: "Log", detail: "Entries, details and privacy" },
    { id: "schedule", title: "Schedule", detail: "Views, slots and reminders" },
    { id: "progress", title: "Progress", detail: "Overview, grid and edit mode" },
    { id: "performance", title: "Performance", detail: "Comparisons and priorities" },
    { id: "leaderboard", title: "Leaderboard", detail: "Rankings and privacy" },
    { id: "workout", title: "Workout", detail: "Templates, sets, timers and history" },
    { id: "chat", title: "Chat", detail: "Group and direct conversations" },
    { id: "journal", title: "Journal", detail: "Rich notes, labels and drawing" },
    { id: "display", title: "Display", detail: "Theme, pages, order and widget guidance" },
  ],
  steps: [
    {
      id: "essential.navigation",
      sectionId: "today",
      target: "tab-bar",
      path: "/",
      title: "Start with the navigation bar",
      copy: "The bottom bar opens HabHub's main pages. Today is your daily home; hidden optional pages can be enabled later from Display settings.",
      primaryLabel: "Show Today",
      anchor: { required: false, waitMs: 1800, padding: 0, radius: 0 },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.today.hero",
      sectionId: "today",
      target: "today-hero",
      path: "/",
      title: "Start with the daily summary",
      copy: "The featured card combines only goals you flagged as tracked. Its bars show tracked-goal completion and to-do completion, and tapping it opens Status.",
      primaryLabel: "Next",
      anchor: { required: true, waitMs: 1800, padding: 7, radius: 18 },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.today.tracked-versus-general",
      sectionId: "today",
      target: "today-tracker-list",
      path: "/",
      title: "Tracked goals and general trackers",
      copy: "A tracked goal counts toward the daily completion result. A general tracker can stay visible for logging and history without affecting that result.",
      primaryLabel: "Next",
      anchor: { required: false, waitMs: 1800 },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "essential.today.open-menu",
      sectionId: "menu",
      target: "menu-button",
      path: "/",
      title: "Open the menu yourself",
      copy: "The profile avatar opens HabHub's menu. Use it whenever you want tracker customization, settings, groups, notifications or guide replay.",
      primaryLabel: "Tap the profile avatar",
      anchor: { required: true, waitMs: 1800, padding: 5, radius: 18 },
      interaction: {
        mode: "practice",
        actionId: "tutorial.navigation.open-menu",
        instruction: "Tap your profile avatar to open the menu.",
        completion: "observed-action",
        autoAdvance: true,
      },
    },
    {
      id: "full.menu.customize",
      sectionId: "menu",
      target: "menu-customize",
      path: "/menu",
      title: "See every tracker in one place",
      copy: "Customize trackers shows everything added to HabHub, what counts as a tracked goal, and the independent order used by Today and Progress.",
      primaryLabel: "Open Customize",
      anchor: { required: true, waitMs: 1800 },
      navigation: { before: "/menu" },
      interaction: {
        mode: "practice",
        actionId: "tutorial.navigation.open-customize",
        instruction: "Tap Customize trackers to open the complete tracker library.",
        completion: "observed-action",
        autoAdvance: true,
      },
    },
    {
      id: "full.customize.overview",
      sectionId: "custom-metric",
      target: "customize-tabs",
      path: "/customize",
      title: "Choose what appears and what counts",
      copy: "All Trackers is your library. Tracked goals controls daily completion, while Today and Progress keep their own visibility and order.",
      primaryLabel: "Next",
      anchor: { required: true, waitMs: 1800, padding: 6, radius: 16 },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.custom.preset-or-name",
      sectionId: "custom-metric",
      target: "customize-add",
      path: "/customize",
      title: "Start ready-made or custom",
      copy: "Choose one ready-made tracker to edit its defaults, select several to add them together, or enter a name, color, icon and reusable type for a custom tracker.",
      primaryLabel: "Next",
      anchor: { required: true, waitMs: 1800 },
      navigation: { before: "/customize" },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "essential.customize.close",
      sectionId: "custom-metric",
      target: "customize-close",
      path: "/customize",
      title: "Return to Today",
      copy: "The tracker library is always available from the menu. Close it now to continue arranging the daily page.",
      primaryLabel: "Tap Close",
      anchor: { required: true, waitMs: 1800, padding: 5, radius: 14 },
      interaction: {
        mode: "practice",
        actionId: "tutorial.navigation.close-customize",
        instruction: "Tap Close to return to Today.",
        completion: "observed-action",
        autoAdvance: true,
      },
    },
    {
      id: "full.today.filters",
      sectionId: "today",
      target: "today-filter",
      path: "/",
      title: "Save focused views",
      copy: "Filters can include selected trackers and selected to-dos. A saved view may stay available as a quick chip or remain hidden until you edit it.",
      primaryLabel: "Open filters",
      anchor: { required: false, waitMs: 1800 },
      interaction: {
        mode: "practice",
        actionId: "tutorial.today.open-filter-sheet",
        instruction: "Tap the current view button to see Tracked goals, All trackers and your saved views.",
        completion: "observed-action",
        autoAdvance: true,
      },
    },
    {
      id: "essential.today.filter-manage",
      sectionId: "today",
      target: "today-filter-manage",
      path: "/",
      title: "Create your own focused view",
      copy: "Saved views can combine selected trackers and to-dos, then stay as quick chips or remain hidden until you need them.",
      primaryLabel: "Tap Manage custom views",
      anchor: { required: true, waitMs: 1800, padding: 5, radius: 14 },
      interaction: {
        mode: "practice",
        actionId: "tutorial.today.open-filter-manager",
        instruction: "Tap Manage custom views to open the filter editor.",
        completion: "observed-action",
        autoAdvance: true,
      },
    },
    {
      id: "full.today.filter-manager",
      sectionId: "today",
      target: "today-view-filter-list",
      path: "/view-filters",
      title: "Save focused views",
      copy: "Filters can include selected trackers and selected to-dos. A saved view may stay available as a quick chip or remain hidden until you edit it.",
      primaryLabel: "Continue",
      anchor: { required: true, waitMs: 1800 },
      navigation: { before: "/view-filters?scope=today", after: "/" },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.today.edit",
      sectionId: "today",
      target: "today-edit",
      path: "/",
      title: "Enter edit mode",
      copy: "Edit mode reveals the same core arrangement tools available under Customize trackers.",
      primaryLabel: "Enter edit mode",
      anchor: { required: false, waitMs: 1800 },
      interaction: {
        mode: "practice",
        actionId: "tutorial.today.enter-edit",
        instruction: "Tap Customize Today to reveal flags, pins, removal and reorder controls.",
        completion: "observed-action",
      },
    },
    {
      id: "full.today.flag",
      sectionId: "today",
      target: "today-goal-flag",
      path: "/",
      title: "Choose what counts",
      copy: "The flag immediately left of the standard checkmark turns a visible tracker into a tracked goal. Turning it off preserves the tracker and its data.",
      primaryLabel: "Toggle the demo flag",
      anchor: { required: false, waitMs: 1800 },
      interaction: {
        mode: "practice",
        actionId: "tutorial.today.toggle-tracked",
        instruction: "Toggle Meditation's flag once, then continue.",
        completion: "observed-action",
      },
    },
    {
      id: "full.today.pin-reorder",
      sectionId: "today",
      target: "today-reorder",
      path: "/",
      title: "Pin and reorder",
      copy: "Pins keep important trackers first. Drag handles change the stable Today order without changing Progress or Leaderboard order.",
      primaryLabel: "Try a reorder",
      anchor: { required: false, waitMs: 1800 },
      interaction: {
        mode: "practice",
        actionId: "tutorial.today.reorder",
        instruction: "Move one demo tracker, then release it in the new position.",
        completion: "observed-action",
      },
    },
    {
      id: "full.today.edit-menu",
      sectionId: "today",
      target: "today-edit-menu",
      path: "/",
      title: "Use the edit shortcuts",
      copy: "History controls the optional mini charts; Add existing restores a tracker; Create opens the tracker builder; Tracked goals manages counted goals; Day ends changes the local daily cutoff.",
      primaryLabel: "Next",
      anchor: { required: false, waitMs: 1800 },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.status.avatar",
      sectionId: "status",
      target: "status-avatar",
      path: "/status",
      title: "Status keeps the body view compact",
      copy: "Your name, Weight, completion percentage and Body Fat flank the avatar while tracked-goal rings remain below it.",
      primaryLabel: "Next",
      anchor: { required: false, waitMs: 1800 },
      navigation: { before: "/status" },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.log.choose",
      sectionId: "log",
      target: "log-header",
      path: "/log",
      title: "Choose a tracker to log",
      copy: "Manual trackers accept an entry. Steps also accepts a manual daily total when device sync is unavailable; most other calculated, device-owned and gym-derived trackers open their history or source.",
      primaryLabel: "Next",
      anchor: { required: true, waitMs: 1800 },
      navigation: { before: "/log" },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.schedule.overview",
      sectionId: "schedule",
      target: "schedule-grid",
      path: "/calendar",
      title: "See the week as one schedule",
      copy: "Schedule combines planned to-dos, app reminders, tracker reminders, logged blocks and workout sessions without turning them into the same data type.",
      primaryLabel: "Next",
      anchor: { required: false, waitMs: 1800 },
      navigation: { before: "/calendar" },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.progress.layouts",
      sectionId: "progress",
      target: "progress-modes",
      path: "/insights",
      title: "Switch between overview and grid map",
      copy: "Overview compares trends. Grid map shows daily completion or intensity. Display settings can expose either layout or both.",
      primaryLabel: "Next",
      anchor: { required: true, waitMs: 1800 },
      navigation: { before: "/insights" },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.progress.range",
      sectionId: "progress",
      target: "progress-range",
      path: "/insights",
      title: "Keep the same date context",
      copy: "Week, month and year ranges share an anchor, so switching layouts keeps the same period. Previous, next and the date picker move that anchor.",
      primaryLabel: "Next",
      anchor: { required: false, waitMs: 1800 },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.performance.range",
      sectionId: "performance",
      target: "performance-range",
      path: "/performance",
      title: "Compare performance over time",
      copy: "Choose day, week, month, year or a custom comparison period. Range values such as screen-time app usage are shown as daily averages, not interval totals.",
      primaryLabel: "Next",
      anchor: { required: false, waitMs: 1800 },
      navigation: { before: "/performance" },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.leaderboard.cards",
      sectionId: "leaderboard",
      target: "leaderboard-cards",
      path: "/group",
      title: "Compare the group fairly",
      copy: "Each card ranks a tracker or a dated challenge. Status-only sharing can show progress without exposing an exact value.",
      primaryLabel: "Next",
      anchor: { required: false, waitMs: 1800 },
      navigation: { before: "/group" },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.workout.modes",
      sectionId: "workout",
      target: "workout-modes",
      path: "/gym",
      title: "Plan, log and review workouts",
      copy: "Workout combines the active session, saved history, exercise progress and performance views. Choose a date when logging a past session.",
      primaryLabel: "Next",
      anchor: { required: false, waitMs: 1800 },
      navigation: { before: "/gym" },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.workout.templates",
      sectionId: "workout",
      target: "workout-templates",
      path: "/gym",
      title: "Start from a template",
      copy: "Personal and admin-published group templates populate exercises, target sets, reps, starting load, notes and saved supersets.",
      primaryLabel: "Choose Full-body strength",
      anchor: { required: false, waitMs: 1800 },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.chat.conversations",
      sectionId: "chat",
      target: "chat-header",
      path: "/chat",
      title: "Group and direct conversations",
      copy: "Switch conversations from the header. Unread state is personal, and muted conversations suppress push alerts without deleting messages.",
      primaryLabel: "Next",
      anchor: { required: true, waitMs: 1800 },
      navigation: { before: "/chat" },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.journal.library",
      sectionId: "journal",
      target: "journal-notes",
      path: "/journal",
      title: "Find notes by date, tracker or label",
      copy: "Journal lists private notes with image and drawing previews. Filters can focus a linked tracker or a hashtag label.",
      primaryLabel: "Create a demo note",
      anchor: { required: false, waitMs: 1800 },
      navigation: { before: "/journal" },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "full.menu.profile",
      sectionId: "menu",
      target: "menu-profile",
      path: "/menu",
      title: "Open the HabHub menu",
      copy: "The menu links profile, cloud and health sync, notifications, display, groups, guides and tracker customization.",
      primaryLabel: "Next",
      anchor: { required: false, waitMs: 1800 },
      navigation: { before: "/menu" },
      interaction: { mode: "observe", completion: "manual" },
    },
    {
      id: "essential.menu.open-display",
      sectionId: "display",
      target: "menu-display",
      path: "/menu",
      title: "Open Display settings",
      copy: "Display controls theme, text size, visible pages, tab order, landing page and the layouts used by Today and Progress.",
      primaryLabel: "Tap Display",
      anchor: { required: true, waitMs: 1800, padding: 5, radius: 14 },
      navigation: { before: "/menu" },
      interaction: {
        mode: "practice",
        actionId: "tutorial.navigation.open-display",
        instruction: "Tap Display to open the app layout controls.",
        completion: "observed-action",
        autoAdvance: true,
      },
    },
    {
      id: "essential.display.layout",
      sectionId: "display",
      target: "display-layout",
      path: "/display-settings",
      title: "Keep only what you use",
      copy: "Show, hide, or reorder optional pages here. You can replay this guide from the menu at any time.",
      primaryLabel: "Finish",
      anchor: { required: true, waitMs: 1800 },
      interaction: { mode: "observe", completion: "manual" },
    },
  ],
};

export const DEFAULT_TUTORIAL_GUIDES: readonly TutorialGuide[] = [
  BASIC_TUTORIAL_GUIDE,
];

/** Backward-compatible alias used by onboarding and guide replay. */
export const BASIC_TUTORIAL_GUIDES = DEFAULT_TUTORIAL_GUIDES;
