import { BASIC_TUTORIAL_GUIDE } from "./basicGuide";
import { TUTORIAL_DAY_ROUTE } from "./routes";
import type { TutorialGuide, TutorialStep } from "./types";

export { BASIC_TUTORIAL_GUIDE } from "./basicGuide";

type StepInput = Omit<TutorialStep, "sectionId" | "anchor" | "interaction"> & {
  target?: string;
  required?: boolean;
  practice?: {
    actionId: `tutorial.${string}`;
    instruction: string;
    completion?: "tap-anchor" | "observed-action";
    autoAdvance?: boolean;
  };
};

const step = (sectionId: string, input: StepInput): TutorialStep => ({
  ...input,
  sectionId,
  anchor: input.target
    ? {
        required: input.required ?? true,
        waitMs: input.required === false ? 900 : 2200,
        padding: 7,
        radius: 16,
      }
    : undefined,
  interaction: input.practice
    ? {
        mode: "practice",
        actionId: input.practice.actionId,
        instruction: input.practice.instruction,
        completion: input.practice.completion ?? "observed-action",
        autoAdvance: input.practice.autoAdvance,
      }
    : { mode: "observe", completion: "manual" },
});

const TODAY_STEPS = [
  step("today", {
    id: "full.today.hero",
    path: "/",
    target: "today-hero",
    title: "Start with the daily summary",
    copy: "The featured card combines only goals you flagged as tracked. Its bars show tracked-goal completion and to-do completion, and tapping it opens Status.",
    primaryLabel: "Next",
  }),
  step("today", {
    id: "full.today.tracked-versus-general",
    path: "/",
    target: "today-tracker-list",
    title: "Tracked goals and general trackers",
    copy: "A tracked goal counts toward the daily completion result. A general tracker can stay visible for logging and history without affecting that result.",
    primaryLabel: "Next",
    required: false,
  }),
  step("today", {
    id: "full.today.todo",
    path: "/",
    target: "today-todo-list",
    title: "Finish a to-do",
    copy: "To-dos have their own completion bar. Completing, skipping, pinning, deadlines, planned times and recurrence stay independent from tracker goals.",
    primaryLabel: "Try the checkmark",
    required: false,
    practice: {
      actionId: "tutorial.today.complete-todo",
      instruction: "Complete the demo grocery to-do. This changes only the isolated tutorial preview.",
    },
  }),
  step("today", {
    id: "full.today.edit",
    path: "/",
    target: "today-edit",
    title: "Enter edit mode",
    copy: "Edit mode reveals the same core arrangement tools available under Customize trackers.",
    primaryLabel: "Enter edit mode",
    required: false,
    practice: {
      actionId: "tutorial.today.enter-edit",
      instruction: "Tap Customize Today to reveal flags, pins, removal and reorder controls.",
    },
  }),
  step("today", {
    id: "full.today.flag",
    path: "/",
    target: "today-goal-flag",
    title: "Choose what counts",
    copy: "The flag immediately left of the standard checkmark turns a visible tracker into a tracked goal. Turning it off preserves the tracker and its data.",
    primaryLabel: "Toggle the demo flag",
    required: false,
    practice: {
      actionId: "tutorial.today.toggle-tracked",
      instruction: "Toggle Meditation's flag once, then continue.",
    },
  }),
  step("today", {
    id: "full.today.history-start",
    path: "/",
    target: "today-tracked-goals",
    title: "Apply tracking from the right date",
    copy: "Tracked-goal history records when a goal starts counting. Applying a change to history can recalculate earlier completion, while starting today leaves prior days intact.",
    primaryLabel: "Next",
    required: false,
  }),
  step("today", {
    id: "full.today.pin-reorder",
    path: "/",
    target: "today-reorder",
    title: "Pin and reorder",
    copy: "Pins keep important trackers first. Drag handles change the stable Today order without changing Progress or Leaderboard order.",
    primaryLabel: "Try a reorder",
    required: false,
    practice: {
      actionId: "tutorial.today.reorder",
      instruction: "Move one demo tracker, then release it in the new position.",
    },
  }),
  step("today", {
    id: "full.today.edit-menu",
    path: "/",
    target: "today-edit-menu",
    title: "Use the edit shortcuts",
    copy: "History controls the optional mini charts; Add existing restores a tracker; Create opens the tracker builder; Tracked goals manages counted goals; Day ends changes the local daily cutoff.",
    primaryLabel: "Next",
    required: false,
  }),
  step("today", {
    id: "full.today.filters",
    path: "/",
    target: "today-filter",
    title: "Save focused views",
    copy: "Filters can include selected trackers and selected to-dos. A saved view may stay available as a quick chip or remain hidden until you edit it.",
    primaryLabel: "Open filters",
    required: false,
    navigation: { after: "/view-filters?scope=today" },
  }),
  step("today", {
    id: "full.today.filter-manager",
    path: "/view-filters",
    target: "today-view-filter-list",
    title: "Save focused views",
    copy: "Filters can include selected trackers and selected to-dos. A saved view may stay available as a quick chip or remain hidden until you edit it.",
    primaryLabel: "Continue",
    required: true,
    navigation: {
      before: "/view-filters?scope=today",
      after: "/",
    },
  }),
  step("today", {
    id: "full.today.all-complete",
    path: "/",
    target: "today-all-complete",
    title: "See a completed day",
    copy: "When every due tracked goal is complete, HabHub shows the all-goals result and the featured outline reaches its completed state.",
    primaryLabel: "Continue",
    required: false,
  }),
  step("status", {
    id: "full.status.avatar",
    path: "/status",
    target: "status-avatar",
    title: "Status keeps the body view compact",
    copy: "Your name, Weight, completion percentage and Body Fat flank the avatar while tracked-goal rings remain below it.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/status" },
  }),
  step("status", {
    id: "full.status.simulator",
    path: "/status",
    target: "status-avatar",
    title: "Preview a possible direction",
    copy: "Tap the avatar to open the non-scientific visual simulator. Weight uses profile height for total size; body fat and lean mass remain independent and can each be disabled.",
    primaryLabel: "Open simulator",
    required: false,
    practice: {
      actionId: "tutorial.status.open-simulator",
      instruction: "Open the simulator and adjust a demo slider. Nothing is saved to the profile.",
    },
  }),
  step("status", {
    id: "full.status.avatar-source",
    path: "/status",
    target: "status-avatar-source",
    title: "Choose the live avatar signal",
    copy: "BMI is the default. Body composition uses both body-fat and lean-mass readings when available; otherwise the avatar falls back safely to BMI.",
    primaryLabel: "Next module",
    required: false,
  }),
] as const;

const SCHEDULE_STEPS = [
  step("schedule", {
    id: "full.schedule.overview",
    path: "/calendar",
    target: "schedule-grid",
    title: "See the week as one schedule",
    copy: "Schedule combines planned to-dos, app reminders, tracker reminders, logged blocks and workout sessions without turning them into the same data type.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/calendar" },
  }),
  step("schedule", {
    id: "full.schedule.all-slot",
    path: "/calendar",
    target: "schedule-all-slot",
    title: "Open a day's complete list",
    copy: "The ALL slot opens every reminder, activity and to-do scheduled for that day, not only all-day tasks.",
    primaryLabel: "Open ALL",
    required: false,
    practice: {
      actionId: "tutorial.schedule.open-all",
      instruction: "Open the demo day's ALL slot, then inspect its items.",
    },
  }),
  step("schedule", {
    id: "full.schedule.slot-create",
    path: "/calendar",
    target: "schedule-hour-slot",
    title: "Create from an empty slot",
    copy: "Double-tap or press and hold a time slot to create a scheduled item at that time. Single-tap an item to open its editor or source page.",
    primaryLabel: "Try the slot",
    required: false,
    practice: {
      actionId: "tutorial.schedule.open-slot-menu",
      instruction: "Press and hold a demo slot until the creation menu opens.",
    },
  }),
  step("schedule", {
    id: "full.schedule.edit-mode",
    path: "/calendar",
    target: "schedule-edit",
    title: "Arrange the schedule",
    copy: "Edit mode lets you reorder visible schedule items and remove personal schedule rows without deleting tracker history.",
    primaryLabel: "Next",
    required: false,
  }),
  step("schedule", {
    id: "full.schedule.views",
    path: "/calendar",
    target: "schedule-view",
    title: "Build schedule views",
    copy: "A schedule view independently chooses to-dos, reminders and logged tracker blocks. The tutorial demo includes Focus day and Health views.",
    primaryLabel: "Next",
    required: false,
  }),
  step("todo", {
    id: "full.todo.deadline-planned",
    path: "/todo-editor",
    target: "todo-timing",
    title: "Deadline and planned time differ",
    copy: "A deadline says when a task is due. A planned start and end reserve time on Schedule. A task can have either or both.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/todo-editor?id=tutorial-todo-plan-week" },
  }),
  step("todo", {
    id: "full.todo.repeat-remind",
    path: "/todo-editor",
    target: "todo-repeat-reminders",
    title: "Repeat the task and its alerts",
    copy: "Task recurrence controls which dates receive an instance. Each reminder can be one-off, relative to the deadline, repeated daily until due, or follow its own cadence.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/todo-editor?id=tutorial-todo-plan-week" },
  }),
  step("schedule", {
    id: "full.schedule.tracker-reminders",
    path: "/reminder-editor",
    target: "reminder-editor",
    title: "Tracker reminders can reserve time",
    copy: "A tracker reminder may include duration, frequency and an end date. The same reminders are also editable from Notifications and the tracker editor.",
    primaryLabel: "Next module",
    required: false,
    navigation: { before: "/reminder-editor?id=tutorial-reminder-reading" },
  }),
] as const;

const LOG_STEPS = [
  step("log", {
    id: "full.log.choose",
    path: "/log",
    target: "log-header",
    title: "Choose a tracker to log",
    copy: "Manual trackers accept an entry. Calculated, device-owned and gym-derived trackers direct you to their history or source instead.",
    primaryLabel: "Next",
    navigation: { before: "/log" },
  }),
  step("log", {
    id: "full.log.time-details",
    path: "/log",
    target: "log-date-time",
    title: "Date and time are explicit",
    copy: "Backdated entries use the selected local day while the recorded time preserves when the event happened. Notes, labels, compound fields and an image add context.",
    primaryLabel: "Next",
    required: false,
  }),
  step("food", {
    id: "full.food.search",
    path: "/log",
    target: "log-food-search",
    title: "Search from the food name",
    copy: "Type a food name and press Search or the keyboard's Search action. Barcode scan is another route; the chosen serving fills calories and available nutrients.",
    primaryLabel: "Open food search",
    required: false,
    navigation: { before: "/log?metric=food", after: "/food-search?q=oats" },
  }),
  step("food", {
    id: "full.food.nutrition",
    path: "/food-search",
    target: "food-search-results",
    title: "Adjust the serving",
    copy: "Choose a match, change its serving multiplier and send those values back to Log. Local and recently used matches are prioritized.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/food-search?q=oats" },
  }),
  step("log", {
    id: "full.log.privacy",
    path: "/log",
    target: "log-visibility",
    title: "Choose who can see this entry",
    copy: "Private keeps the value account-only. Status shares goal state without the exact value. Group shares the exact value with authorized group members.",
    primaryLabel: "Try the menu",
    required: false,
    navigation: { before: "/log?metric=tutorial_wellbeing" },
    practice: {
      actionId: "tutorial.log.visibility",
      instruction: "Open the compact visibility menu and choose Status for the demo entry.",
    },
  }),
  step("timer", {
    id: "full.timer.setup",
    path: "/timer",
    target: "timer-setup",
    title: "Time a compatible tracker",
    copy: "Choose a timer-enabled tracker, stopwatch or countdown, optional threshold alerts, and whether finishing should log the elapsed value automatically.",
    primaryLabel: "Start demo timer",
    required: false,
    navigation: { before: "/timer" },
    practice: {
      actionId: "tutorial.timer.start",
      instruction: "Start the isolated Reading countdown.",
    },
  }),
  step("timer", {
    id: "full.timer.active",
    path: "/timer",
    target: "timer-active",
    title: "Timers survive navigation",
    copy: "Pause, resume, add laps or finish from the timer page. The floating overlay and local notification keep a live timer usable while you visit another page or lock the phone.",
    primaryLabel: "Next module",
    required: false,
  }),
] as const;

const PROGRESS_STEPS = [
  step("progress", {
    id: "full.progress.layouts",
    path: "/insights",
    target: "progress-modes",
    title: "Switch between overview and grid map",
    copy: "Overview compares trends. Grid map shows daily completion or intensity. Display settings can expose either layout or both.",
    primaryLabel: "Next",
    navigation: { before: "/insights" },
  }),
  step("progress", {
    id: "full.progress.range",
    path: "/insights",
    target: "progress-range",
    title: "Keep the same date context",
    copy: "Week, month and year ranges share an anchor, so switching layouts keeps the same period. Previous, next and the date picker move that anchor.",
    primaryLabel: "Next",
    required: false,
  }),
  step("progress", {
    id: "full.progress.overview",
    path: "/insights",
    target: "progress-overview-card",
    title: "Read goal trends",
    copy: "Tracked goals summarize all-goal days and individual goal completion. Up to the first six ordered tracked goals appear in the compact overview bars.",
    primaryLabel: "Next",
    required: false,
  }),
  step("progress", {
    id: "full.progress.grid-day",
    path: "/insights",
    target: "progress-grid-cell",
    title: "Every grid date opens its day",
    copy: "Week, month and year cells are real date actions. The year cells intentionally stay tiny and open Daily detail when tapped precisely.",
    primaryLabel: "Open a day",
    required: false,
    practice: {
      actionId: "tutorial.progress.open-day",
      instruction: "Tap a demo date cell to open Daily detail.",
      autoAdvance: true,
    },
  }),
  step("daily-detail", {
    id: "full.daily-detail.sections",
    path: TUTORIAL_DAY_ROUTE,
    target: "daily-detail-summary",
    title: "Inspect one day",
    copy: "Daily detail combines completion, selected logs, to-dos, photos and private comparison tools for the chosen date.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: TUTORIAL_DAY_ROUTE },
  }),
  step("daily-detail", {
    id: "full.daily-detail.filter-compare",
    path: TUTORIAL_DAY_ROUTE,
    target: "daily-detail-filter",
    title: "Filter and compare",
    copy: "Choose which logs appear, open their source entries, or compare a progress photo with another date and save the collage.",
    primaryLabel: "Next",
    required: false,
  }),
  step("progress", {
    id: "full.progress.edit",
    path: "/insights",
    target: "progress-edit",
    title: "Curate Progress independently",
    copy: "Progress has its own selection, pins and order. Add existing restores a card, Create opens the tracker builder, and saved filters focus the list without deleting anything.",
    primaryLabel: "Next module",
    required: false,
    navigation: { before: "/insights" },
  }),
] as const;

const PERFORMANCE_STEPS = [
  step("performance", {
    id: "full.performance.range",
    path: "/performance",
    target: "performance-range",
    title: "Compare performance over time",
    copy: "Choose day, week, month, year or a custom comparison period. Range values such as screen-time app usage are shown as daily averages, not interval totals.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/performance" },
  }),
  step("performance", {
    id: "full.performance.priorities",
    path: "/performance",
    target: "performance-filters",
    title: "Focus the analysis",
    copy: "Prioritize gaining, steady, needs-focus or missing trackers, or jump to the strongest result and next opportunity.",
    primaryLabel: "Next",
    required: false,
  }),
  step("performance", {
    id: "full.performance.edit",
    path: "/performance",
    target: "performance-edit",
    title: "Choose the performance tiles",
    copy: "Pin, reorder, hide or add compatible trackers. Performance ordering remains separate from Today and Progress.",
    primaryLabel: "Next module",
    required: false,
  }),
] as const;

const SOCIAL_STEPS = [
  step("leaderboard", {
    id: "full.leaderboard.cards",
    path: "/group",
    target: "leaderboard-cards",
    title: "Compare the group fairly",
    copy: "Each card ranks a tracker or a dated challenge. Status-only sharing can show progress without exposing an exact value.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/group" },
  }),
  step("leaderboard", {
    id: "full.leaderboard.edit",
    path: "/group",
    target: "leaderboard-edit",
    title: "Edit your leaderboard view",
    copy: "Your personal card order, pins, selected metrics and hidden untracked cards do not rewrite the group's tracker configuration.",
    primaryLabel: "Next",
    required: false,
  }),
  step("challenges", {
    id: "full.challenge.create",
    path: "/group",
    target: "leaderboard-create-challenge",
    title: "Challenge specific friends",
    copy: "Choose a tracker, exact target, date and participants. Only authorized exact entries can decide a challenge winner.",
    primaryLabel: "Open creator",
    required: false,
    practice: {
      actionId: "tutorial.challenge.open-create",
      instruction: "Open the challenge editor, then close it without saving.",
    },
  }),
  step("leaderboard", {
    id: "full.leaderboard.detail",
    path: "/leaderboard-detail",
    target: "leaderboard-detail-chart",
    title: "Open ranking detail",
    copy: "Change the period, filter people and metrics, inspect the chart, and compare progress photos where sharing permits it.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/leaderboard-detail?metrics=steps&period=week" },
  }),
  step("comparison", {
    id: "full.comparison.stats",
    path: "/member/tutorial-mina",
    target: "comparison-stats",
    title: "Compare with a friend",
    copy: "Date ranges, competitive stats, head-to-head results, chart people and filters are all available on the friend comparison page.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/member/tutorial-mina" },
  }),
  step("badges", {
    id: "full.badges.showcase",
    path: "/member/tutorial-you",
    target: "badge-showcase-picker",
    title: "Choose your showcase",
    copy: "On your own profile, choose up to five earned badges below the showcase card. Other members see the selected set.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/member/tutorial-you" },
  }),
  step("badges", {
    id: "full.badges.cabinet",
    path: "/badges",
    target: "badge-cabinet",
    title: "Understand the badge cabinet",
    copy: "Filter by person, tracker, status and date. Challenge-winner badges count repeated wins and display milestone progress; badges are derived, not manually assigned.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/badges" },
  }),
  step("groups", {
    id: "full.groups.manage",
    path: "/groups",
    target: "groups-list",
    title: "Switch, join or invite",
    copy: "Groups keeps account-owned data separate while allowing you to switch active group, join with a code or share an invite.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/groups" },
  }),
  step("groups", {
    id: "full.groups.settings",
    path: "/group-settings",
    target: "group-settings",
    title: "Manage group-owned configuration",
    copy: "Admins control group trackers, scoring, shared workout templates, theme, join approval and members. Entry privacy remains enforced separately.",
    primaryLabel: "Next module",
    required: false,
    navigation: { before: "/group-settings" },
  }),
] as const;

const WORKOUT_STEPS = [
  step("workout", {
    id: "full.workout.modes",
    path: "/gym",
    target: "workout-modes",
    title: "Plan, log and review workouts",
    copy: "Workout combines the active session, saved history, exercise progress and performance views. Choose a date when logging a past session.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/gym" },
  }),
  step("workout", {
    id: "full.workout.templates",
    path: "/gym",
    target: "workout-templates",
    title: "Start from a template",
    copy: "Personal and admin-published group templates populate exercises, target sets, reps, starting load, notes and saved supersets.",
    primaryLabel: "Choose Full-body strength",
    required: false,
    practice: {
      actionId: "tutorial.workout.choose-template",
      instruction: "Choose the demo Full-body strength template.",
    },
  }),
  step("workout", {
    id: "full.workout.session",
    path: "/gym",
    target: "workout-session-details",
    title: "Describe the session",
    copy: "Set date, duration, intensity, notes and visibility. Calories can use Session MET or the set-aware estimate, with an explicit manual override when needed.",
    primaryLabel: "Next",
    required: false,
  }),
  step("workout", {
    id: "full.workout.exercise-set",
    path: "/gym",
    target: "workout-exercises",
    title: "Log exercises and sets",
    copy: "Exercises support load and reps, reps-only or duration. Complete individual sets, record rest, add sets, and pair a second movement as a superset.",
    primaryLabel: "Complete a demo set",
    required: false,
    practice: {
      actionId: "tutorial.workout.complete-set",
      instruction: "Mark one demo squat set complete.",
    },
  }),
  step("workout", {
    id: "full.workout.guided-timer",
    path: "/gym",
    target: "workout-guided-timer",
    title: "Use the guided workout timer",
    copy: "Start, pause and advance through work and rest. Local notifications keep the current set usable while HabHub is minimized or the phone is locked.",
    primaryLabel: "Next",
    required: false,
  }),
  step("workout", {
    id: "full.workout.save-history",
    path: "/gym",
    target: "workout-save",
    title: "Save and review",
    copy: "Saving creates one standardized session used by history, muscle volume, exercise trends, estimated 1RM, calories and group-visible derived trackers.",
    primaryLabel: "Next",
    required: false,
  }),
  step("workout", {
    id: "full.workout.exercise-detail",
    path: "/gym-exercise",
    target: "gym-exercise-progress",
    title: "Track exercise progress",
    copy: "Review seven days, thirty days or all history, compare best load and estimated one-rep max, and save a personal load, rep or 1RM target.",
    primaryLabel: "Next module",
    required: false,
    navigation: { before: "/gym-exercise?key=back_squat" },
  }),
] as const;

const CHAT_JOURNAL_STEPS = [
  step("chat", {
    id: "full.chat.conversations",
    path: "/chat",
    target: "chat-header",
    title: "Group and direct conversations",
    copy: "Switch conversations from the header. Unread state is personal, and muted conversations suppress push alerts without deleting messages.",
    primaryLabel: "Next",
    navigation: { before: "/chat" },
  }),
  step("chat", {
    id: "full.chat.composer",
    path: "/chat",
    target: "chat-composer",
    title: "Send text or an image",
    copy: "The composer follows the native keyboard and returns smoothly when it hides. Notifications include the sender and message text when allowed.",
    primaryLabel: "Next",
    required: false,
  }),
  step("journal", {
    id: "full.journal.library",
    path: "/journal",
    target: "journal-notes",
    title: "Find notes by date, tracker or label",
    copy: "Journal lists private notes with image and drawing previews. Filters can focus a linked tracker or a hashtag label.",
    primaryLabel: "Create a demo note",
    required: false,
    navigation: { before: "/journal", after: "/note-editor" },
  }),
  step("journal", {
    id: "full.journal.labels",
    path: "/note-editor",
    target: "note-trackers-labels",
    title: "Link trackers and create hashtags",
    copy: "Type # followed by a word for a searchable label, or link one note to several trackers without creating a tracker entry.",
    primaryLabel: "Next",
    required: false,
  }),
  step("journal", {
    id: "full.journal.formatting",
    path: "/note-editor",
    target: "note-formatting",
    title: "Format like a general note app",
    copy: "Use headings, bold, italic, strike, bullets, checklists, quotes, text color and links. The color palette remains open while you choose colors, and normal multiline text wraps inside the note.",
    primaryLabel: "Try bold text",
    required: false,
    practice: {
      actionId: "tutorial.journal.format",
      instruction: "Type a short demo sentence and apply Bold.",
    },
  }),
  step("journal", {
    id: "full.journal.image-drawing",
    path: "/note-editor",
    target: "note-drawing",
    title: "Draw over text or an image",
    copy: "Attach an image, turn on the independent drawing layer, select pen width and color, draw freely, undo strokes or clear the layer without breaking the text.",
    primaryLabel: "Next module",
    required: false,
  }),
] as const;

const SETTINGS_STEPS = [
  step("menu", {
    id: "full.menu.profile",
    path: "/menu",
    target: "menu-profile",
    title: "Open the HabHub menu",
    copy: "The menu links profile, cloud and health sync, notifications, display, groups, guides and tracker customization.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/menu" },
  }),
  step("menu", {
    id: "full.menu.customize",
    path: "/menu",
    target: "menu-customize",
    title: "See every tracker in one place",
    copy: "Customize trackers shows everything added to HabHub, what counts as a tracked goal, and the independent order used by Today and Progress.",
    primaryLabel: "Open Customize",
    navigation: { before: "/menu", after: "/customize" },
  }),
  step("custom-metric", {
    id: "full.customize.overview",
    path: "/customize",
    target: "customize-tabs",
    title: "Choose what appears and what counts",
    copy: "All Trackers is your library. Tracked goals controls daily completion, while Today and Progress keep their own visibility and order.",
    primaryLabel: "Next",
    navigation: { before: "/customize", after: "/settings" },
  }),
  step("settings", {
    id: "full.settings.cloud",
    path: "/settings",
    target: "settings-cloud-account",
    title: "Understand cloud sync",
    copy: "Review account status, sync now, connected devices, sign out and account deletion. The tutorial preview never writes to your account or cloud.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/settings" },
  }),
  step("settings", {
    id: "full.settings.health",
    path: "/settings",
    target: "settings-health",
    title: "Connect health data deliberately",
    copy: "Choose data types, source preferences, history depth and sync frequency. Health permissions are operating-system surfaces: HabHub can open them and resume afterward, but cannot spotlight controls inside them.",
    primaryLabel: "Next",
    required: false,
  }),
  step("notifications", {
    id: "full.notifications.controls",
    path: "/notifications",
    target: "notifications-controls",
    title: "Choose exactly what interrupts you",
    copy: "Control group activity, chat, membership, streaks, badges, reminders, workouts, cycle estimates and quiet hours. Tracker reminders remain editable from their tracker too.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/notifications" },
  }),
  step("notifications", {
    id: "full.notifications.battery",
    path: "/notifications",
    target: "battery-optimization",
    title: "Allow reliable Android background work",
    copy: "HabHub can request the Android battery-optimization settings so scheduled background sync is less likely to be delayed. The final choice happens in the operating-system page.",
    primaryLabel: "Next",
    required: false,
  }),
  step("display", {
    id: "full.display.appearance",
    path: "/display-settings",
    target: "personal-theme",
    title: "Set appearance and locale",
    copy: "Choose personal accent, group-theme override, language, compact layout, dark mode, text size, week start, time format and default landing page.",
    primaryLabel: "Next",
    navigation: { before: "/display-settings" },
  }),
  step("display", {
    id: "full.display.pages",
    path: "/display-settings",
    target: "display-layout",
    title: "Choose pages and navigation order",
    copy: "Show or hide optional pages, reorder the navigation bar, configure Today tiles and completion indicator, and choose available Progress layouts.",
    primaryLabel: "Next",
  }),
  step("display", {
    id: "full.display.widgets",
    path: "/display-settings",
    target: "display-widgets-info",
    title: "Add the Status widget from Android",
    copy: "HabHub keeps the Status Avatar widget updated from app snapshots. Home-screen widget placement belongs to the Android launcher, so the guide can explain it but cannot practice that system action inside HabHub.",
    primaryLabel: "Next module",
    required: false,
  }),
] as const;

const METRIC_STEPS = [
  step("metric-detail", {
    id: "full.metric-detail.summary",
    path: "/metric-detail",
    target: "metric-detail-summary",
    title: "Read one tracker's story",
    copy: "A tracker page combines the chosen day or range, current result, goal state, history visualization, records, notes, related to-dos and shortcuts to log, edit or schedule it.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/metric-detail?metric=steps" },
  }),
  step("metric-detail", {
    id: "full.metric-detail.visuals",
    path: "/metric-detail",
    target: "metric-detail-chart",
    title: "Visuals follow tracker settings",
    copy: "Selected-day, range, Progress overview and grid-map visuals can use progress, completion, bars, lines, both, intensity or completion according to compatible settings.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/metric-detail?metric=tutorial_wellbeing" },
  }),
  step("screen-time", {
    id: "full.screen-time.access",
    path: "/metric-detail",
    target: "screen-time-breakdown",
    title: "Screen Time stays device-private",
    copy: "On Android, grant Usage Access to see approximate foreground time and per-app breakdown. The report and app limits stay on this device; iOS supports manual tracker logs until the separately approved Family Controls entitlement exists.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/metric-detail?metric=screen_time" },
  }),
  step("screen-time", {
    id: "full.screen-time.averages-limits",
    path: "/metric-detail",
    target: "screen-time-app-list",
    title: "Read averages and set app limits",
    copy: "Multi-day ranges show average daily app usage and durations as hours and minutes. On today's report, tap a bell to set or remove a private daily app limit.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/metric-detail?metric=screen_time" },
  }),
  step("fasting", {
    id: "full.fasting.clock",
    path: "/metric-detail",
    target: "fasting-clock",
    title: "Configure the fasting window",
    copy: "Adjust the normal start and fasting duration. The clock shows fasting and eating windows without requiring a manual numeric log.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/metric-detail?metric=intermittent_fasting" },
  }),
  step("fasting", {
    id: "full.fasting.manual-auto",
    path: "/metric-detail",
    target: "fasting-controls",
    title: "Start manually or use meals",
    copy: "Start and End control a personal live fast. Auto mode can infer the start from the last meal and complete it at the next first-food entry; manual controls remain available.",
    primaryLabel: "Try Start or End",
    required: false,
    navigation: { before: "/metric-detail?metric=intermittent_fasting" },
    practice: {
      actionId: "tutorial.fasting.toggle",
      instruction: "Toggle the isolated demo fast once.",
    },
  }),
  step("custom-metric", {
    id: "full.custom.preset-or-name",
    path: "/metric-editor",
    target: "metric-editor-basics",
    title: "Start ready-made or custom",
    copy: "Choose one ready-made tracker to edit its defaults, select several to add them together, or enter a name, color, icon and reusable type for a custom tracker.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/metric-editor" },
  }),
  step("custom-metric", {
    id: "full.custom.entry-behavior",
    path: "/metric-editor",
    target: "metric-editor-entry",
    title: "Choose the data behavior",
    copy: "Entry types are Number, Done / not done, Note, Photo or Calculated. Numeric trackers can add, average, use latest, highest or lowest daily entries.",
    primaryLabel: "Next",
    required: false,
  }),
  step("custom-metric", {
    id: "full.custom.goal",
    path: "/metric-editor",
    target: "metric-editor-goal",
    title: "Define success",
    copy: "Enable or remove the target, choose at least, at most, exact or completion behavior, use a healthy range, and decide between daily progress and a journey from the first reading.",
    primaryLabel: "Open Advanced",
    required: false,
    navigation: { before: "/metric-editor?id=tutorial_meditation" },
  }),
  step("custom-metric", {
    id: "full.custom.adaptive-visuals",
    path: "/metric-editor",
    target: "metric-editor-visuals",
    title: "Adapt targets and charts",
    copy: "Advanced settings can calculate a target from the previous completed week, month, year or all history using average or median, and customize compatible chart styles for detail and Progress.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/metric-editor?id=tutorial_meditation" },
  }),
  step("custom-metric", {
    id: "full.custom.submetrics",
    path: "/metric-editor",
    target: "metric-editor-submetrics",
    title: "Collect related fields together",
    copy: "Submetrics can have their own units, targets, range charts, progress bars, health source and connected tracker. Render them separately or merge them with a display template.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/metric-editor?id=tutorial_wellbeing" },
  }),
  step("custom-metric", {
    id: "full.custom.health-behavior",
    path: "/metric-editor",
    target: "metric-editor-behavior",
    title: "Connect sources and destinations",
    copy: "Advanced behavior covers health mapping, manual-entry availability, timer support, Today, Progress and group sections, sharing default, tracking start, reminders, progress alerts and goal schedule.",
    primaryLabel: "Next",
    required: false,
    navigation: { before: "/metric-editor?id=tutorial_wellbeing" },
  }),
  step("custom-metric", {
    id: "full.custom.formula",
    path: "/metric-editor",
    target: "metric-editor-formula",
    title: "Build a safe calculated tracker",
    copy: "Insert tracker identifiers and use arithmetic, comparisons, parentheses and MIN, MAX, AVERAGE, ROUND, ABS, CLAMP or IF. HabHub parses this expression safely; it never evaluates arbitrary code.",
    primaryLabel: "Validate the demo formula",
    required: false,
    navigation: { before: "/metric-editor?id=tutorial_focus_score" },
    practice: {
      actionId: "tutorial.metric.validate-formula",
      instruction: "Run validation on the demo Focus score formula.",
    },
  }),
  step("custom-metric", {
    id: "full.custom.save",
    path: "/metric-editor",
    target: "metric-editor-save",
    title: "Save into the tutorial preview",
    copy: "Saving updates only the isolated demo while this guide is active. Leaving the tutorial restores your account exactly as it was.",
    primaryLabel: "Finish full guide",
    required: false,
    navigation: { before: "/metric-editor?id=tutorial_focus_score" },
  }),
] as const;

export const FULL_TUTORIAL_GUIDE: TutorialGuide = {
  id: "full-app",
  version: 1,
  title: "Complete HabHub guide",
  detail: "Hands-on guidance for every major page, tracker type and advanced setting",
  icon: "map-outline",
  path: "/",
  sections: [
    { id: "today", title: "Today", detail: "Daily goals, to-dos and edit mode" },
    { id: "status", title: "Status", detail: "Avatar, body facts and tracked goals" },
    { id: "schedule", title: "Schedule", detail: "Views, slots and reminders" },
    { id: "todo", title: "To-dos", detail: "Deadlines, planned times and recurrence" },
    { id: "log", title: "Log", detail: "Entries, details and privacy" },
    { id: "food", title: "Food", detail: "Search, scan and nutrition" },
    { id: "timer", title: "Timers", detail: "Stopwatch, countdown and auto-log" },
    { id: "progress", title: "Progress", detail: "Overview, grid and edit mode" },
    { id: "daily-detail", title: "Daily detail", detail: "One day's goals, logs and photos" },
    { id: "performance", title: "Performance", detail: "Comparisons and priorities" },
    { id: "leaderboard", title: "Leaderboard", detail: "Rankings and privacy" },
    { id: "challenges", title: "Challenges", detail: "Friend competitions" },
    { id: "comparison", title: "Friend comparison", detail: "Stats, charts and photos" },
    { id: "badges", title: "Badges", detail: "Cabinet, progress and showcase" },
    { id: "groups", title: "Groups", detail: "Membership and administration" },
    { id: "workout", title: "Workout", detail: "Templates, sets, timers and history" },
    { id: "chat", title: "Chat", detail: "Group and direct conversations" },
    { id: "journal", title: "Journal", detail: "Rich notes, labels and drawing" },
    { id: "menu", title: "Menu", detail: "Profile and feature navigation" },
    { id: "settings", title: "Cloud and health", detail: "Sync, sources and data controls" },
    { id: "notifications", title: "Notifications", detail: "Alerts, reminders and background reliability" },
    { id: "display", title: "Display", detail: "Theme, pages, order and widget guidance" },
    { id: "metric-detail", title: "Tracker detail", detail: "History, charts and records" },
    { id: "screen-time", title: "Screen Time", detail: "Private usage, averages and limits" },
    { id: "fasting", title: "Intermittent fasting", detail: "Windows, manual and automatic sessions" },
    { id: "custom-metric", title: "Custom trackers", detail: "Creation, formulas and advanced visuals" },
  ],
  steps: [
    ...TODAY_STEPS,
    ...SCHEDULE_STEPS,
    ...LOG_STEPS,
    ...PROGRESS_STEPS,
    ...PERFORMANCE_STEPS,
    ...SOCIAL_STEPS,
    ...WORKOUT_STEPS,
    ...CHAT_JOURNAL_STEPS,
    ...SETTINGS_STEPS,
    ...METRIC_STEPS,
  ],
};

const MODULE_ICONS: Readonly<Record<string, string>> = {
  today: "today-outline",
  status: "body-outline",
  schedule: "calendar-outline",
  todo: "checkbox-outline",
  log: "add-circle-outline",
  food: "restaurant-outline",
  timer: "timer-outline",
  progress: "grid-outline",
  "daily-detail": "calendar-number-outline",
  performance: "analytics-outline",
  leaderboard: "trophy-outline",
  challenges: "flag-outline",
  comparison: "people-outline",
  badges: "ribbon-outline",
  groups: "people-circle-outline",
  workout: "barbell-outline",
  chat: "chatbubbles-outline",
  journal: "journal-outline",
  menu: "menu-outline",
  settings: "cloud-outline",
  notifications: "notifications-outline",
  display: "color-palette-outline",
  "metric-detail": "pulse-outline",
  "screen-time": "phone-portrait-outline",
  fasting: "hourglass-outline",
  "custom-metric": "options-outline",
};

/** Every full-guide section can also be replayed as a focused module. */
export const MODULE_TUTORIAL_GUIDES: readonly TutorialGuide[] =
  FULL_TUTORIAL_GUIDE.sections!.map((section) => {
    const steps = FULL_TUTORIAL_GUIDE.steps.filter(
      (tutorialStep) => tutorialStep.sectionId === section.id,
    );
    const first = steps[0];
    return {
      id: `module:${section.id}`,
      version: FULL_TUTORIAL_GUIDE.version,
      title: `${section.title} guide`,
      detail: section.detail ?? `Focused walkthrough of ${section.title}`,
      icon: MODULE_ICONS[section.id] ?? "compass-outline",
      path: first?.navigation?.before ?? first?.path ?? FULL_TUTORIAL_GUIDE.path,
      sections: [section],
      steps,
    };
  });

export const TUTORIAL_GUIDES: readonly TutorialGuide[] = [
  BASIC_TUTORIAL_GUIDE,
  FULL_TUTORIAL_GUIDE,
  ...MODULE_TUTORIAL_GUIDES,
];

export const TUTORIAL_ANCHOR_INVENTORY = [...new Set(
  TUTORIAL_GUIDES.flatMap((guide) => guide.steps.flatMap((item) => item.target ? [item.target] : [])),
)].sort();

export const TUTORIAL_ROUTE_INVENTORY = [...new Set(
  TUTORIAL_GUIDES.flatMap((guide) => guide.steps.flatMap((item) => [
    item.path,
    item.navigation?.before,
    item.navigation?.after,
  ].filter((route): route is string => Boolean(route)))),
)].sort();
