import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import React, { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { Button, Card, Chip, IconButton, PageHeader, Screen } from '@/src/components/ui';
import { energyFormulaVariables } from '@/src/domain/energy';
import { evaluateFormula, formulaIdentifiers } from '@/src/domain/formula';
import { useApp } from '@/src/state/AppProvider';
import { palette } from '@/src/theme';
import { Aggregation, MetricDataType, NewMetric, RankingDirection, Visibility } from '@/src/types';

const ICONS=['walk-outline','fitness-outline','heart-outline','leaf-outline','water-outline','star-outline','restaurant-outline','flash-outline','trending-down-outline','barbell-outline','bicycle-outline','body-outline','bed-outline','book-outline','bulb-outline','cafe-outline','calendar-outline','camera-outline','checkmark-circle-outline','clipboard-outline','cloud-outline','code-outline','diamond-outline','earth-outline','eye-outline','fast-food-outline','flag-outline','flame-outline','flower-outline','football-outline','game-controller-outline','golf-outline','hand-left-outline','happy-outline','headset-outline','home-outline','hourglass-outline','language-outline','medkit-outline','moon-outline','musical-notes-outline','nutrition-outline','paw-outline','pencil-outline','people-outline','pulse-outline','reader-outline','ribbon-outline','rocket-outline','school-outline','shirt-outline','speedometer-outline','sunny-outline','tennisball-outline','thermometer-outline','time-outline','trophy-outline','umbrella-outline','watch-outline','accessibility-outline'] as const;
const COLORS=['#176B4D','#3478D4','#7756D9','#D95852','#E08A32','#337B7B','#B05C8C','#7B6A33'];
type FormulaState={kind:'idle'|'valid'|'invalid';message?:string};

export default function MetricEditor(){
  const {id}=useLocalSearchParams<{id?:string}>();const {state,addMetric,updateMetric,deleteMetric}=useApp();const metric=id&&id!=='new'?state.metrics.find((item)=>item.id===id):undefined;
  const [name,setName]=useState(metric?.name??'');const [unit,setUnit]=useState(metric?.unit??'');const [dataType,setDataType]=useState<MetricDataType>(metric?.dataType??'number');const [goal,setGoal]=useState(String(metric?.goal.target??''));const [formula,setFormula]=useState(metric?.formula??'');const [icon,setIcon]=useState(metric?.icon??ICONS[0]);const [color,setColor]=useState(metric?.color??COLORS[0]);const [visibility,setVisibility]=useState<Visibility>(metric?.defaultVisibility??'group');const [aggregation,setAggregation]=useState<Aggregation>(metric?.aggregation??'sum');const [ranking,setRanking]=useState<RankingDirection>(metric?.rankingDirection??'higher');const [formulaState,setFormulaState]=useState<FormulaState>({kind:'idle'});
  function insert(token:string){setFormula((current)=>`${current}${current&&!current.endsWith(' ')?' ':''}${token}${['+','-','*','/'].includes(token)?' ':''}`);setFormulaState({kind:'idle'});}
  function validate(showAlert=false){try{const known=Object.fromEntries(state.metrics.map((item)=>[item.id,1]));if(metric&&formulaIdentifiers(formula).includes(metric.id))throw new Error('A calculated metric cannot use itself.');const unknown=formulaIdentifiers(formula).filter((identifier)=>!(identifier in known)&&!['bmr','daily_activity','baseline','daily_energy'].includes(identifier));if(unknown.length)throw new Error(`Unknown metrics: ${unknown.join(', ')}`);const preview=evaluateFormula(formula,{...known,...energyFormulaVariables(state.settings.energyProfile,state.settings.baselineCalories)});const message=`Formula works · example result ${Number(preview.toFixed(2))}`;setFormulaState({kind:'valid',message});if(showAlert)Alert.alert('Formula works',message);return true;}catch(error){const message=error instanceof Error?error.message:'Invalid formula.';setFormulaState({kind:'invalid',message});Alert.alert('Formula needs attention',message);return false;}}
  function save(){const target=dataType==='text'?0:Number(goal.replace(',','.'));if(!name.trim())return Alert.alert('Name your metric','Enter a clear name.');if(dataType!=='text'&&(!Number.isFinite(target)||target<0))return Alert.alert('Check the goal','Enter a valid goal.');if(dataType==='calculated'&&(!formula.trim()||!validate(false)))return;const common={name:name.trim(),unit:unit.trim(),icon,color,dataType,goal:{kind:dataType==='boolean'||dataType==='photo'?'complete' as const:'at_least' as const,target},rankingDirection:dataType==='boolean'||dataType==='photo'?'higher' as const:ranking,defaultVisibility:visibility,formula:dataType==='calculated'?formula.trim():undefined};if(metric)updateMetric(metric.id,{...common,aggregation:dataType==='text'?'latest':aggregation});else addMetric(common as NewMetric);router.back();}
  function remove(){if(!metric)return;const dependents=state.metrics.filter((item)=>item.formula&&formulaIdentifiers(item.formula).includes(metric.id));if(dependents.length)return Alert.alert('Metric is used by a formula',`Remove it from ${dependents.map((item)=>item.name).join(', ')} first.`);Alert.alert(`Delete ${metric.name}?`,'Its entries will also be deleted.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>{deleteMetric(metric.id);router.back();}}]);}
  return <Screen keyboardShouldPersistTaps="handled"><PageHeader eyebrow="Metric editor" title={metric?`Edit ${metric.name}`:'Create metric'} subtitle="This editor closes independently, so the metric list stays tidy." showMenu={false} action={<IconButton icon="close" label="Close" onPress={()=>router.back()}/>}/>
    <Card><Text style={styles.label}>Name</Text><TextInput value={name} onChangeText={setName} placeholder="Protein, mood, reading…" placeholderTextColor={palette.faint} style={styles.input}/><Text style={styles.label}>Data type</Text><View style={styles.options}>{(['number','boolean','text','calculated'] as MetricDataType[]).map((type)=><Chip key={type} label={type==='boolean'?'Yes / no':type==='text'?'Free text':type[0].toUpperCase()+type.slice(1)} selected={dataType===type} onPress={()=>{setDataType(type);if(type==='boolean')setGoal('1');}}/>)}</View>
    {dataType!=='text'?<View style={styles.columns}><View style={styles.column}><Text style={styles.label}>Unit</Text><TextInput value={unit} onChangeText={setUnit} style={styles.input} placeholder="kcal, kg, min" placeholderTextColor={palette.faint}/></View><View style={styles.column}><Text style={styles.label}>Daily goal</Text><TextInput value={goal} onChangeText={setGoal} keyboardType="decimal-pad" style={styles.input} placeholder="100" placeholderTextColor={palette.faint}/></View></View>:null}
    {dataType==='number'?<><Text style={styles.label}>Daily aggregation</Text><View style={styles.options}>{(['sum','latest','average','max','min'] as Aggregation[]).map((item)=><Chip key={item} label={item} selected={aggregation===item} onPress={()=>setAggregation(item)}/>)}</View></>:null}
    {dataType==='number'||dataType==='calculated'?<><Text style={styles.label}>Ranking</Text><View style={styles.options}>{(['higher','lower','closest'] as RankingDirection[]).map((item)=><Chip key={item} label={item==='closest'?'Closest to goal':`${item} wins`} selected={ranking===item} onPress={()=>setRanking(item)}/>)}</View></>:dataType==='boolean'?<Text style={styles.hint}>Yes/no metrics rank by completed days and completion percentage.</Text>:null}
    {dataType==='calculated'?<><Text style={styles.label}>Formula builder</Text><TextInput value={formula} onChangeText={(value)=>{setFormula(value);setFormulaState({kind:'idle'});}} autoCapitalize="none" multiline style={[styles.input,styles.formula,formulaState.kind==='invalid'&&styles.invalid,formulaState.kind==='valid'&&styles.valid]} placeholder="bmr + daily_activity + exercise - food" placeholderTextColor={palette.faint}/>{formulaState.kind!=='idle'?<View style={[styles.validation,formulaState.kind==='valid'?styles.validationGood:styles.validationBad]}><Ionicons name={formulaState.kind==='valid'?'checkmark-circle':'alert-circle'} size={19} color={formulaState.kind==='valid'?palette.primary:palette.red}/><Text style={[styles.validationText,{color:formulaState.kind==='valid'?palette.primary:palette.red}]}>{formulaState.message}</Text></View>:null}<Text style={styles.picker}>PROFILE VALUES</Text><View style={styles.options}>{['bmr','daily_activity','daily_energy'].map((value)=><Chip key={value} label={value.replace('_',' ')} onPress={()=>insert(value)}/>)}</View><Text style={styles.picker}>METRICS</Text><View style={styles.options}>{state.metrics.filter((item)=>item.id!==metric?.id&&item.dataType!=='text').map((item)=><Chip key={item.id} label={item.name} icon={item.icon as keyof typeof Ionicons.glyphMap} onPress={()=>insert(item.id)}/>)}</View><Text style={styles.picker}>OPERATORS</Text><View style={styles.options}>{['+','-','*','/','(',')','MIN(','MAX(','IF('].map((value)=><Chip key={value} label={value} onPress={()=>insert(value)}/>)}</View><Button label="Validate formula" variant="ghost" icon="checkmark-circle-outline" onPress={()=>validate(true)}/></>:null}
    <Text style={styles.label}>Default entry visibility</Text><View style={styles.options}><Chip label="Only me" icon="lock-closed-outline" selected={visibility==='private'} onPress={()=>setVisibility('private')}/><Chip label="Goal status" icon="shield-checkmark-outline" selected={visibility==='status'} onPress={()=>setVisibility('status')}/><Chip label="Exact value" icon="people-outline" selected={visibility==='group'} onPress={()=>setVisibility('group')}/></View><Text style={styles.label}>Icon ({ICONS.length} choices)</Text><View style={styles.icons}>{ICONS.map((option,index)=><Pressable key={option} onPress={()=>{setIcon(option);setColor(COLORS[index%COLORS.length]);}} style={[styles.icon,icon===option&&{borderColor:color,backgroundColor:`${color}18`}]}><Ionicons name={option} size={20} color={COLORS[index%COLORS.length]}/></Pressable>)}</View><View style={styles.actions}>{metric?<View style={styles.delete}><Button label="Delete" variant="danger" onPress={remove}/></View>:null}<View style={styles.save}><Button label={metric?'Save changes':'Create metric'} icon="checkmark" onPress={save}/></View></View></Card>
  </Screen>;
}
const styles=StyleSheet.create({label:{color:palette.ink,fontSize:11,fontWeight:'900',marginTop:7,marginBottom:7},input:{borderWidth:1,borderColor:palette.border,borderRadius:13,paddingHorizontal:13,paddingVertical:12,color:palette.ink,fontSize:14,marginBottom:10},columns:{flexDirection:'row',gap:10},column:{flex:1},options:{flexDirection:'row',flexWrap:'wrap',gap:7,marginBottom:10},hint:{color:palette.primary,fontSize:10,lineHeight:15,backgroundColor:palette.primarySoft,borderRadius:12,padding:10,marginBottom:10},formula:{minHeight:80,textAlignVertical:'top'},invalid:{borderColor:palette.red,backgroundColor:'#FFF8F7'},valid:{borderColor:'#79B894',backgroundColor:'#F5FBF7'},validation:{flexDirection:'row',alignItems:'center',gap:7,borderRadius:12,padding:10,marginTop:-4,marginBottom:10},validationGood:{backgroundColor:palette.primarySoft},validationBad:{backgroundColor:'#FFF1F0'},validationText:{flex:1,fontSize:10,fontWeight:'800'},picker:{color:palette.muted,fontSize:9,fontWeight:'900',letterSpacing:.8,marginBottom:7},icons:{flexDirection:'row',flexWrap:'wrap',gap:7,marginBottom:14},icon:{width:39,height:39,borderRadius:12,borderWidth:1.5,borderColor:palette.border,alignItems:'center',justifyContent:'center'},actions:{flexDirection:'row',gap:9},delete:{width:100},save:{flex:1}});
