import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { Card, IconButton, PageHeader, Screen, SectionHeader } from '@/src/components/ui';
import { useApp } from '@/src/state/AppProvider';
import { palette } from '@/src/theme';
import { NotificationSettings } from '@/src/types';

export default function NotificationsScreen(){
  const {state,updateSettings}=useApp();const value=state.settings.notifications;
  const groupMetrics=state.metrics.filter((metric)=>metric.scoreWeight>0&&metric.dataType!=='text');
  function patch(changes:Partial<NotificationSettings>){updateSettings({notifications:{...value,...changes}});}
  function toggleMetric(id:string){patch({metricIds:value.metricIds.includes(id)?value.metricIds.filter((item)=>item!==id):[...value.metricIds,id]});}
  return <Screen keyboardShouldPersistTaps="handled"><PageHeader eyebrow="Alerts" title="Notifications" subtitle="Choose exactly what can interrupt you." showMenu={false} action={<IconButton icon="close" label="Close" onPress={()=>router.back()}/>}/>
    <Card><ToggleRow icon="notifications" title="Push notifications" copy="Master switch for notifications on this device" enabled={value.pushEnabled} onPress={()=>patch({pushEnabled:!value.pushEnabled})}/></Card>
    <SectionHeader title="Group activity"/><Card style={styles.list}><ToggleRow icon="pulse-outline" title="Tracked metric activity" copy="Notify when friends log selected group metrics" enabled={value.groupMetricActivity} onPress={()=>patch({groupMetricActivity:!value.groupMetricActivity})}/>{groupMetrics.map((metric)=><Pressable key={metric.id} disabled={!value.groupMetricActivity} onPress={()=>toggleMetric(metric.id)} style={[styles.metric,!value.groupMetricActivity&&styles.disabled]}><View style={[styles.metricIcon,{backgroundColor:`${metric.color}18`}]}><Ionicons name={metric.icon as keyof typeof Ionicons.glyphMap} size={18} color={metric.color}/></View><Text style={styles.metricName}>{metric.name}</Text><Ionicons name={value.metricIds.includes(metric.id)?'checkbox':'square-outline'} size={21} color={value.metricIds.includes(metric.id)?palette.primary:palette.faint}/></Pressable>)}</Card>
    <SectionHeader title="Other notifications"/><Card style={styles.list}><ToggleRow icon="chatbubbles-outline" title="Chat messages" copy="Group and private messages" enabled={value.chatMessages} onPress={()=>patch({chatMessages:!value.chatMessages})}/><ToggleRow icon="trophy-outline" title="Badges & winners" copy="Awards and finalized period winners" enabled={value.badgesAndWinners} onPress={()=>patch({badgesAndWinners:!value.badgesAndWinners})}/><ToggleRow icon="alarm-outline" title="Logging reminders" copy="Your configured daily reminders" enabled={value.reminders} onPress={()=>patch({reminders:!value.reminders})}/></Card>
    <SectionHeader title="Quiet hours"/><Card><ToggleRow icon="moon-outline" title="Quiet hours" copy="Hold non-urgent alerts during this window" enabled={value.quietHoursEnabled} onPress={()=>patch({quietHoursEnabled:!value.quietHoursEnabled})}/>{value.quietHoursEnabled?<View style={styles.times}><View style={styles.time}><Text style={styles.label}>From</Text><TextInput value={value.quietHoursStart} onChangeText={(quietHoursStart)=>patch({quietHoursStart})} style={styles.input}/></View><View style={styles.time}><Text style={styles.label}>Until</Text><TextInput value={value.quietHoursEnd} onChangeText={(quietHoursEnd)=>patch({quietHoursEnd})} style={styles.input}/></View></View>:null}</Card>
    <Text style={styles.note}>Demo mode stores these preferences locally. Once push delivery is connected, the same switches are sent to the notification service.</Text>
  </Screen>;
}
function ToggleRow({icon,title,copy,enabled,onPress}:{icon:keyof typeof Ionicons.glyphMap;title:string;copy:string;enabled:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={styles.row}><View style={styles.rowIcon}><Ionicons name={icon} size={20} color={palette.primary}/></View><View style={styles.copy}><Text style={styles.title}>{title}</Text><Text style={styles.copyText}>{copy}</Text></View><View style={[styles.toggle,enabled&&styles.toggleOn]}><View style={[styles.knob,enabled&&styles.knobOn]}/></View></Pressable>;}
const styles=StyleSheet.create({list:{paddingVertical:4,paddingHorizontal:13},row:{minHeight:65,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderBottomColor:palette.border},rowIcon:{width:38,height:38,borderRadius:12,backgroundColor:palette.primarySoft,alignItems:'center',justifyContent:'center'},copy:{flex:1},title:{color:palette.ink,fontSize:13,fontWeight:'900'},copyText:{color:palette.muted,fontSize:9,lineHeight:14,marginTop:2},toggle:{width:43,height:25,borderRadius:13,padding:3,backgroundColor:'#D9DFDA'},toggleOn:{backgroundColor:palette.primary},knob:{width:19,height:19,borderRadius:10,backgroundColor:palette.white},knobOn:{marginLeft:18},metric:{minHeight:52,flexDirection:'row',alignItems:'center',gap:9,paddingHorizontal:4},metricIcon:{width:34,height:34,borderRadius:11,alignItems:'center',justifyContent:'center'},metricName:{flex:1,color:palette.ink,fontSize:12,fontWeight:'800'},disabled:{opacity:.4},times:{flexDirection:'row',gap:10,marginTop:12},time:{flex:1},label:{color:palette.muted,fontSize:9,fontWeight:'800',marginBottom:5},input:{borderWidth:1,borderColor:palette.border,borderRadius:11,padding:10,color:palette.ink,textAlign:'center',fontWeight:'800'},note:{color:palette.muted,fontSize:10,lineHeight:15,textAlign:'center',marginTop:13}});
